version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:8080
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - drupal_data:/bitnami

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=YAM428
      - MARIADB_PASSWORD=030718112
      - MARIADB_DATABASE=FINAL
    volumes:
      - mariadb_data:/bitnami

  webserver:
    image: nginx
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - drupal_data:/var/www/html

  certificate:
    image: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  drupal_data:
  mariadb_data:

